backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include # 導入個人應用程式
from django.conf import settings
from django.conf.urls.static import static

from . import views  # 導入專案的 views.py(自己手動建的)

urlpatterns = [
    # http://127.0.0.1:8000/<str:template_name>.html 
    # 以確保操作index時其餘頁面都能正常連結到
    path('<str:template_name>.html', views.render_template, name='render_template'),


    # admin-APP (後台管理者)
    # http://127.0.0.1:8000/
    path('', include('admins.urls')), # 包含 admin 的 URL

    # http://127.0.0.1:8000/admins_api/
    path('admins_api/', include('admins_api.urls')), # 包含 admins_api 的 URL

    # Users-APP (後台會員)
    # http://127.0.0.1:8000/users/ 
    path('users/', include('users.urls')), # 包含 users 的 URL
    # http://127.0.0.1:8000/users_api/ 
    path('users_api/', include('users_api.urls')),  # 包含 users_api 的 URL

    # member-api APP (串前台vue會員)
    # http://127.0.0.1:8000/member_api/ 
    path('member_api/', include('member_api.urls')), # 包含 member_api 的 URL

    path('store/', include('products.urls')),
    path('store_backend/', include('products_backend.urls')),

    #http://127.0.0.1:8000/cart/ 
    path('cart/', include('cart.urls')),

    #http://127.0.0.1:8000/cart_api/ 
    path('cart_api/', include('cart_api.urls')),
    
    #http://127.0.0.1:8000/promotions/
    path('promotions/', include('promotions.urls')),

    # http://127.0.0.1:8000/commission/ 
    path('commission/', include('commission.urls')),
    
    path('Movies/', include('Movies.urls')),
    path('Games/', include('Games.urls')),
    path('Animations/', include('Animations.urls')),
    path('Discussion_board/', include('Discussion_board.urls')),
    path("api/", include("discussion.urls")),
    path('api/', include('entertainment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

backend/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
#後臺管理端
urlpatterns = [
    path('', views.order_list, name='orders'),
]

backend/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views



app_name = 'users'
urlpatterns = [
    # http://127.0.0.1:8000/admin/users/
    path('', views.index, name="index" ),
    # http://127.0.0.1:8000/admin/users/404
    path('404/', views.page404, name="404" ),

    # http://127.0.0.1:8000/users/register
    path('register/', views.register, name="create" ),
    # http://127.0.0.1:8000/users/edit/
    path('edit/', views.edit, name="edit" ),
    # http://127.0.0.1:8000/users/delete/
    path('delete/<int:id>', views.delete, name="delete" ),
    
    # http://127.0.0.1:8000/users/hand_verify/
    path('hand_verify/', views.hand_verify, name="hand_verify" ),
    # http://127.0.0.1:8000/users/login/
    path('login/', views.login, name='login'),
    # http://127.0.0.1:8000/users/logout/
    path('logout/', views.logout, name='logout'),
    # http://127.0.0.1:8000/users/signup/
    path('signup/', views.signup, name="signup"),


    # http://127.0.0.1:8000/users/reset/
    path('reset/', views.reset, name="reset"),
    # http://127.0.0.1:8000/users/reset_confirm/
    path('reset_confirm/', views.reset_confirm, name="reset_confirm"),

    
    # http://127.0.0.1:8000/users/email_change/
    path('email_change/', views.email_change, name="email_change"),
    # http://127.0.0.1:8000/users/email_change_confirm/
    path('email_change_confirm/<str:uidb64>/<str:token>/', views.email_change_confirm, name='email_change_confirm'),
    # http://127.0.0.1:8000/users/email_reconfirm/
    path('email_reconfirm/<str:token>/', views.email_reconfirm, name='email_reconfirm'),
    # http://127.0.0.1:8000/users/phone_change/
    path('phone_change/', views.phone_change, name="phone_change"),
    # http://127.0.0.1:8000/users/phone_change_confirm/
    path('phone_change_confirm/<str:uidb64>/<str:token>/', views.phone_change_confirm, name='phone_change_confirm'),
    # http://127.0.0.1:8000/users/phone_reconfirm/
    path('phone_reconfirm/<str:token>/', views.phone_reconfirm, name='phone_reconfirm'),

    # http://127.0.0.1:8000/users/personal/
    path('personal/', views.personal, name='personal'),
    
    # # http://127.0.0.1:8000/users/verify-code/
    # path('verify-code/', views.verify_code, name='verify_code'),

    # http://127.0.0.1:8000/users/dashboard/
    path('dashboard/', views.dashboard, name='dashboard'),
]

backend/users_api/urls.py
from django.urls import path
from . import views  # 導入視圖

app_name = "users_api"
urlpatterns = [
    # http://127.0.0.1:8000/admin/users_api/
    path('', views.index, name="index"),


    # http://127.0.0.1:8000/users_api/register
    path('register/', views.register),
    # http://127.0.0.1:8000/users_api/checkname/
    path('checkname/', views.checkname ),
    # http://127.0.0.1:8000/users_api/checkphone/
    path('checkphone/', views.checkphone ),
    # http://127.0.0.1:8000/users_api/checkemail/
    path('checkemail/', views.checkemail ),
    # http://127.0.0.1:8000/users_api/checkpassword/
    path('checkpassword/', views.checkpassword ),
    # http://127.0.0.1:8000/users_api/search/
    path('search/', views.search, name='search' ),
    # http://127.0.0.1:8000/users_api/signup
    path('signup/', views.signup, name='signup'),
        # http://127.0.0.1:8000/users_api/personal/
    path('personal/', views.personal ),
    # http://127.0.0.1:8000/users_api/privacy_setting/
    path('privacy_setting/', views.privacy_setting, name="privacy_setting" ),


    # http://127.0.0.1:8000/users_api/send_reset_password/
    path('send_reset_password/', views.send_reset_password, name='send_reset_password'),
    # http://127.0.0.1:8000/users_api/request-verification/
    path('request-verification/', views.request_verification, name='request_verification'),
    # http://127.0.0.1:8000/users_api/send_verification_email/
    path('send_verification_email/', views.send_verification_email, name='send_verification_email'),
    # http://127.0.0.1:8000/users_api/verify_code/
    path('verify_code/', views.verify_code, name='verify_code'),
    # http://127.0.0.1:8000/users_api/reset_confirm
    path('reset_confirm/', views.reset_confirm, name='reset_confirm'),
    # http://127.0.0.1:8000/users_api/email_change/
    path('email_change/', views.email_change, name='email_change'),
    # http://127.0.0.1:8000/users_api/email_change_confirm/<str:token>/
    path('email_change_confirm/<str:token>/', views.email_change_confirm, name='email_change_confirm'),
    # http://127.0.0.1:8000/users_api/email_change_form/
    path('email_change_form/<str:code>/', views.email_change_form, name='email_change_form'),

    
    # http://127.0.0.1:8000/users_api/verify-email/
    path('verify-email/<str:token>/', views.verify_email, name='verify_email'),
    # http://127.0.0.1:8000/users_api/resend-verify-email/
    path('resend-verify-email/', views.resend_verify_email, name='resend_verify_email'),

    
    # http://127.0.0.1:8000/users_api/reset_email/
    path('reset_email/', views.reset_email, name='reset_email'),
    # http://127.0.0.1:8000/users_api/reconfirm_email/<str:token>/
    path('reconfirm_email/<str:token>/', views.reconfirm_email, name='reconfirm_email'),
    # http://127.0.0.1:8000/users_api/reset_phone/
    path('reset_phone/', views.reset_phone, name='reset_phone'),
    # http://127.0.0.1:8000/users_api/reconfirm_phone/<str:token>/
    path('reconfirm_phone/<str:token>/', views.reconfirm_phone, name='reconfirm_phone'),


    # http://127.0.0.1:8000/users_api/phone_change/
    path('phone_change/', views.phone_change, name='phone_change'),
    # http://127.0.0.1:8000/users_api/phone_change_confirm/<str:token>/
    path('phone_change_confirm/<str:token>/', views.phone_change_confirm, name='phone_change_confirm'),
    # http://127.0.0.1:8000/users_api/phone_change_form/<str:code>/
    path('phone_change_form/<str:code>/', views.phone_change_form, name='phone_change_form'),
]

backend/users/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class MemberBasic(models.Model):
    user_id = models.AutoField(primary_key=True)
    user_name = models.CharField(unique=True, max_length=50)
    user_password = models.CharField(max_length=128, null=True)
    user_phone = models.CharField(unique=True, max_length=10, null=True)
    user_email = models.CharField(unique=True, max_length=120)
    user_nickname = models.CharField(max_length=20, blank=True, null=True)
    user_gender = models.CharField(max_length=17, blank=True, null=True)
    user_birth = models.DateField(blank=True, null=True)
    user_address = models.TextField(blank=True, null=True)
    vip_status = models.IntegerField(blank=True, null=True)
    # user_avatar = models.CharField(max_length=255, blank=True, null=True)
    user_avatar = models.ImageField(upload_to='avatars/', default='avatars/default.png')
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'member_basic'


class MemberLogin(models.Model):
    login_id = models.AutoField(primary_key=True)
    user = models.ForeignKey('users.MemberBasic', models.DO_NOTHING)
    provider = models.CharField(max_length=50)
    google_user_id = models.CharField(unique=True, max_length=50, blank=True, null=True)
    line_user_id = models.CharField(unique=True, max_length=50, blank=True, null=True)
    fb_user_id = models.CharField(unique=True, max_length=50, blank=True, null=True)
    access_token = models.CharField(unique=True, max_length=128, blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'member_login'


class MemberIndextype(models.Model):
    type_id = models.AutoField(primary_key=True)
    user = models.ForeignKey('users.MemberBasic', models.DO_NOTHING)
    type_name = models.CharField(max_length=50, blank=True, null=True)
    sort_order = models.IntegerField()
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'member_indextype'
        unique_together = ('user', 'type_name')  # 確保用戶的喜好項目是唯一的


class MemberPhotos(models.Model):
    photo_id = models.AutoField(primary_key=True)
    user = models.ForeignKey('users.MemberBasic', models.DO_NOTHING)
    photo_url = models.CharField(max_length=255)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'member_photos'


class MemberPrivacy(models.Model):
    privacy_id = models.AutoField(primary_key=True)
    user = models.ForeignKey('users.MemberBasic', models.DO_NOTHING)
    phone_verified = models.IntegerField(blank=True, null=True)
    email_verified = models.IntegerField(blank=True, null=True)
    account_verify = models.IntegerField(blank=True, null=True)
    activity_checked = models.IntegerField(blank=True, null=True)
    double_verify = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'member_privacy'


class MemberVerify(models.Model):
    verify_id = models.AutoField(primary_key=True)
    user = models.ForeignKey('users.MemberBasic', models.DO_NOTHING)
    change_value = models.CharField(max_length=255, blank=True, null=True)
    verification_code = models.CharField(max_length=6)
    verification_token = models.CharField(max_length=64, blank=True, null=True)
    verification_type = models.CharField(max_length=15)
    code_used = models.IntegerField(blank=True, null=True)
    token_used = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    expires_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'member_verify'

backend/users/templates/users/hand_verify.html
{% extends "[BASE]ALL.html" %}

{% block app_title %}
<h2>發送驗證信</h2>
{% endblock %}

{% block app_content %}
<!--
    檔案上傳表單的必要設定
    1. form 標籤 enctype="multipart/form-data"
    2. <input type="file" name="userimage" />
    -->
        <div class="d-grid gap-2 col-6 mx-auto">
            <form class="app-search-form" id="searchForm">
                {% csrf_token %}
                <input type="text" placeholder="Search  (姓名.手機.信箱)" name="search" class="form-control search-input" id="search"/>
                <button type="submit" class="btn search-btn btn-primary" value="Search" id="submitBtn">
                <i class="fa-solid fa-magnifying-glass"></i>
              </button>
            </form>
        </div>
        <div id="searchResults"></div>
        <hr>   
            <div class="mb-3">
                <input type="hidden" id="userid" name="userid" value="{{member.user_id}}">
                <label for="userphone" class="form-label">原始手機</label>
                <input type="text" class="form-control" id="userphone" name="userphone" value="{{member.user_phone}}" disabled>
                <label for="useremail" class="form-label">原始電子郵箱</label>
                <input type="email" class="form-control" id="useremail" name="useremail" value="{{member.user_email}}" disabled>
                <label for="userpassword" class="form-label">原始密碼</label>
                <input type="password" class="form-control" id="userpassword" name="userpassword" value="{{member.user_password}}" disabled>
            </div>
            <div class="d-grid gap-2 col-3 mx-auto">
                <a class="btn btn-secondary" href="#"  id="resetEmailBtn" onclick="sendEmailChange()">修改郵箱-發送驗證碼</a>
                <a class="btn btn-info" href="#"  id="resetPhoneBtn" onclick="sendPhoneChange()">修改手機-發送驗證碼</a>
                <a class="btn btn-warning" href="#"  id="resetPasswordBtn" onclick="sendResetpPassword()">忘記密碼-發送驗證碼</a>
            </div>
            <hr>
            <!-- <div class="mb-3">
                <label for="newphone" class="form-label">修改手機號</label>
                <input type="text" class="form-control" id="newphone" name="newphone">
                <label for="newemail" class="form-label">修改電子郵箱</label>
                <input type="email" class="form-control" id="newemail" name="newemail">
            </div>
            <div class="d-grid gap-2 col-4 mx-auto">
                <button class="btn app-btn-primary" type="submit" onclick="return confirm('即將修改本次操作，請問是否確定?~')">提交修改手機/郵箱</button>
            </div> -->
            <a href="{% url 'users:index'%}" class="btn btn-outline-primary me-md-2">回上一頁</a>
{% endblock %}

{% block app_script %}
<script>
    const searchInput  = document.querySelector("#search");
    const searchResults = document.querySelector("#searchResults"); 
    const searchBtn  = document.querySelector("#submitBtn");
    const searchForm = document.querySelector("#searchForm");
    const userphone = document.querySelector("#userphone");
    const useremail = document.querySelector("#useremail");
    const userpassword = document.querySelector("#userpassword");
    const userid = document.querySelector("#userid");

    // 填充輸入框的函數
    function fillUserData(member) {
        userid.value = member.user_id;
        userphone.value = member.user_phone;
        useremail.value = member.user_email;
        userpassword.value = member.user_password;
        // 注意：出於安全考慮，我們通常不會直接顯示密碼
        // 如果確實需要顯示密碼，請確保有適當的安全措施
        // userpassword.value = '********'; // 或者留空，取決於你的需求
    }

    const sendResetpPassword = async () => {
        const email = useremail.value;
        const userid = document.getElementById('userid').value;
        if (email && userid) {
            try {
                const response = await fetch(`{% url 'users_api:send_reset_password' %}`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify({
                        email: email,
                        userid: userid
                    })
                });
                const data = await response.json();

                if (data.status === 'success') {
                    alert('重置密碼-驗證信已發送，請提醒用戶留意郵箱。');
                } else {
                    alert('發送驗證信失敗，請稍後再試。');
                }
            } catch (error) {
                console.error('Error:', error);
                alert('發送驗證信時發生錯誤，請稍後再試。');
            }
        } else {
            alert('請先搜索並選擇一個用戶。');
        }
    };

    const sendEmailChange = async () => {
        const email = useremail.value;
        const userid = document.getElementById('userid').value;
        if (email && userid) {
            try {
                const response = await fetch(`{% url 'users_api:reset_email' %}`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify({
                        email: email,
                        userid: userid
                    })
                });
                
                const data = await response.json();

                if (response.ok) {
                    alert(data.message || '修改郵箱-驗證信已發送，請提醒用戶留意信箱。');
                } else {
                    alert(`發送驗證信失敗：${data.message || '請稍後再試'}`);
                }
            } catch (error) {
                    console.error('Error:', error);
                    alert('發送驗證信時發生錯誤，請稍後再試。');
            }
        } else {
            alert('請先搜索並選擇一個用戶。');
        }
};

    const sendPhoneChange = async () => {
        const phone = userphone.value;
        const email = useremail.value;
        if (phone && email) {
            try {
                const response = await fetch(`{% url 'users_api:reset_phone' %}`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify({
                        phone: phone,
                        email: email
                    })
                });
                
                const data = await response.json();

                if (response.ok) {
                    alert(data.message || '修改手機-驗證信已發送，請提醒用戶留意信箱。');
                } else {
                    alert(`發送驗證信失敗：${data.message || '請稍後再試'}`);
                }
            } catch (error) {
                console.error('Error:', error);
                alert('發送驗證信時發生錯誤，請稍後再試。');
            }
        } else {
            alert('請先搜索並選擇一個用戶。');
        }
    };

    //將輸入的"資料"傳到 users_api 檢查是否存在
    searchForm.addEventListener("submit", async (event)=>{
        event.preventDefault();
        const searchValue = searchInput.value.trim();

        // 檢查輸入是否為空
        if (searchValue.length === 0) {
            searchResults.innerHTML = ''; // 清空結果
            return;
        }
        
        // 1.  call api 取得資料
        const response = await fetch(`/users_api/search/?search=${encodeURIComponent(searchValue)}`);
    const dataInfo = await response.json();

        searchResults.innerHTML = '';

        // 2. 判斷傳到 API 的資料是否已存在資料庫
        if (dataInfo.length > 0) {
            dataInfo.forEach(member => {
                const memberElement = document.createElement('div');
                memberElement.textContent = `用戶 ID： ${member.user_id}，姓名： ${member.user_name}`;
                memberElement.addEventListener('click', () => {
                    // 點擊會員時，把對應資料填充輸入框
                    fillUserData(member);
                });    
            searchResults.appendChild(memberElement);
        });
        // 自動填充第一個搜索結果
        fillUserData(dataInfo[0]);
    } else {
        searchResults.innerText = '沒有匹配的會員';
        // 清空輸入框
        userid.value = '';
        userphone.value = '';
        useremail.value = '';
        userpassword.value = '';
    }
    // 清空搜索輸入框
    searchForm.reset();
    
});
</script>
{% endblock %}

backend/users/templates/users/index.html
{% extends '[BASE]ALL.html' %}

{% load static %}

{% block app_css %}
<style>
    .text-highlight {
        color: #ff0000 !important;
        transition: color 0.3s ease;
    }
</style>
{% endblock %}


{% block app_title %}
<h3>用戶資料列表</h3>
{% endblock %}


{% block app_content %}
<!-- <head>
    <link rel="stylesheet" href="{% static 'path/to/your/styles.css' %}">
</head> -->

<div class="d-flex align-items-center justify-content-between">
    <a href="{% url 'users:create' %}" class="btn btn-outline-primary">新增用戶</a>
    <form class="d-flex ms-auto" role="search" id="searchForm">
        <input class="form-control me-2" type="search" placeholder="Search-姓名.手機.信箱" aria-label="Search" id="search">
        <button type="submit" class="btn app-btn-primary" id="submitBtn"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
</div>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" id="message-{{ forloop.counter }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

<div id="searchResults"></div>
<hr>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>用戶 ID</th>
            <th>姓名</th>
            <th>手機</th>
            <th>電子郵箱</th>
            <th>暱稱</th>
            <th>性別</th>
            <th>生日</th>
            <th>會員等級</th>
            <th>頭像</th>
            <th>編輯</th>
        </tr>
    </thead>
    <tbody>
        {% for member in members %}
        <tr id="member-{{ member.user_id }}">
            <td>{{ member.user_id }}</td>
            <td>{{ member.user_name }}</td>
            <td>{{ member.user_phone }}</td>
            <td>{{ member.user_email }}</td>
            <td>{{ member.user_nickname }}</td>
            <td>{{ member.user_gender }}</td>
            <td>{{ member.user_birth }}</td>
            <td>{{ member.vip_status }}</td>

            <td>
                <img style="height: 80px;" 
     src="{% if member.avatar_url %}{{ member.avatar_url }}{% else %}{{ MEDIA_URL }}{{ member.user_avatar }}{% endif %}" 
     alt="{{ member.user_name }}">
                
                <!-- <img style="height: 80px;" src="{{ MEDIA_URL }}{{ member.user_avatar }}" alt="{{ member.user_name }}"></td> -->
            <td>
                <a href="{% url 'users:personal' %}?id={{ member.user_id }}" class="btn btn-outline-primary">個人頁面</a>
                <a href="{% url 'users:edit' %}?id={{ member.user_id }}" class="btn btn-outline-primary">修改資料</a>
                <!-- <a href="{% url 'users:hand_verify' %}?id={{ member.user_id }}"  class = "btn btn-outline-primary">發驗證信</a> -->
                <a href="{% url 'users:delete' member.user_id %}" class="btn btn-outline-danger" onclick="return confirm('提醒您，本次操作將刪除該會員所有資料，請問是否確定?~')">刪除</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}


{% block app_script %}
<script>
    const searchInput  = document.querySelector("#search");
    const searchResults = document.querySelector("#searchResults"); 
    const searchBtn  = document.querySelector("#submitBtn");
    const searchForm = document.querySelector("#searchForm");

    //將輸入的"資料"傳到 users_api 檢查是否存在
    searchForm .addEventListener("submit", async (event)=>{
        event.preventDefault();
        const searchValue = searchInput.value.trim();

        // 檢查輸入是否為空
        if (searchValue.length === 0) {
            searchResults.innerHTML = ''; // 清空結果
            return;
        }
        
        // 1.  call api 取得資料
        const response = await fetch(`/users_api/search/?search=${encodeURIComponent(searchValue)}`);
        const dataInfo = await response.json();

        searchResults.innerHTML = '';

        // 2. 判斷傳到 API 的資料是否已存在資料庫
        if (dataInfo.length > 0) {
            dataInfo.forEach(member => {
                const memberElement = document.createElement('div');
                memberElement.textContent = `用戶 ID： ${member.user_id}，姓名： ${member.user_name}， 手機： ${member.user_phone}， 電子郵箱： ${member.user_email}`;
                searchResults.appendChild(memberElement);

                // 自動滾動到匹配的會員資料行
                const memberRow = document.getElementById(`member-${member.user_id}`);
                if (memberRow) {
                    memberRow.scrollIntoView({ behavior: 'smooth', block: 'center' });
                    memberRow.querySelectorAll('td').forEach(td => td.classList.add('text-highlight'));
                    setTimeout(() => {
                        memberRow.querySelectorAll('td').forEach(td => td.classList.remove('text-highlight'));
                    }, 3000);
                }
            });
        } else {
            searchResults.innerText = '沒有匹配的會員';
        }
        searchInput.value = '';
    });

    document.addEventListener('DOMContentLoaded', function() {
    {% for message in messages %}
        setTimeout(function() {
            var alert = document.getElementById('message-{{ forloop.counter }}');
            if (alert) {
                alert.classList.remove('show'); 
                setTimeout(function() {
                    alert.remove(); 
                }, 150); // 等待 150 毫秒後再移除
            }
        }, 3000); // 3秒後執行
    {% endfor %}
});
</script>
{% endblock %}